### PR TITLE
Fix nil pointer panic in getPackageInfo

### LINKED ISSUE #1782: [Bug] Plan fails on elasticstack_fleet_integration_policy
**Describe the bug**
I have deployed 100+ integration policies. It now crashes on plan with:
panic: runtime error: invalid memory address or nil pointer dereference

The first time this occurred I assumed a corrupt plan so I manually removed all the policies and applied again. it worked fine for a bit and the same error has now occurred.

**To Reproduce**
1. I deploy a 100+ integration policies based on YAML generated from our integration packages code base.
2. Running initial plan and deploy works successfully
3. A subsequent plan crashes. There is no indication of what changed to cause the crash as there were no intentional changes.

**Expected behavior**
Subsequent plan and apply succeeds.

**Debug output**
Using trace in the plan generates no additional debug info
```
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
...
Stack trace from the terraform-provider-elasticstack_v0.14.2 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18bd1aa]

goroutine 108 [running]:
github.com/elastic/terraform-provider-elasticstack/internal/fleet/integration_policy.getPackageInfo({0x2207250, 0x7a4f4672ed0}, 0x7a4f3fc7940, {0x7a4f4713ca0, 0x4}, {0x7a4f4713ca8, 0x5})
        github.com/elastic/terraform-provider-elasticstack/internal/fleet/integration_policy/resource.go:94 +0x3ea
github.com/elastic/terraform-provider-elasticstack/internal/fleet/integration_policy.(*integrationPolicyResource).Read(0x7a4f3fc2a58, {0x2207250, 0x7a4f4672ed0}, {{{{0x2214818, 0x7a4f42a98c0}, {0x1dc0180, 0x7a4f42a90e0}}, {0x22190e0, 0x7a4f4098500}}, 0x0, ...}, ...)
        github.com/elastic/terraform-provider-elasticstack/internal/fleet/integration_policy/read.go:62 +0x61b
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0x7a4f3c2c308, {0x2207250, 0x7a4f4672ed0}, 0x7a4f4218e60, 0x7a4f3c13538)
        github.com/hashicorp/terraform-plugin-framework@v1.17.0/internal/fwserver/server_readresource.go:156 +0xbdc
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0x7a4f3c2c308, {0x2207250?, 0x7a4f4672de0?}, 0x7a4f4218dc0)
        github.com/hashicorp/terraform-plugin-framework@v1.17.0/internal/proto6server/server_readresource.go:71 +0x585
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ReadResource(0x7a4f3c20480, {0x2207250?, 0x7a4f4672b10?}, 0x7a4f4218dc0)
        github.com/hashicorp/terraform-plugin-mux@v0.21.0/tf6muxserver/mux_server_ReadResource.go:35 +0x190
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0x7a4f3cd2b40, {0x2207250?, 0x7a4f4672330?}, 0x7a4f4212850)
        github.com/hashicorp/terraform-plugin-go@v0.29.0/tfprotov6/tf6server/server.go:863 +0x2f3
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x20973c0, 0x7a4f3cd2b40}, {0x2207250, 0x7a4f4672330}, 0x7a4f4153e80, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.29.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:753 +0x1a9
google.golang.org/grpc.(*Server).processUnaryRPC(0x7a4f39c4600, {0x2207250, 0x7a4f46722a0}, 0x7a4f41bc600, 0x7a4f3d94ea0, 0x362a4f8, 0x0)
        google.golang.org/grpc@v1.75.1/server.go:1431 +0xfdc
google.golang.org/grpc.(*Server).handleStream(0x7a4f39c4600, {0x2208438, 0x7a4f3ce29c0}, 0x7a4f41bc600)
        google.golang.org/grpc@v1.75.1/server.go:1842 +0xb88
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.75.1/server.go:1061 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 35
        google.golang.org/grpc@v1.75.1/server.go:1072 +0x11d

Error: The terraform-provider-elasticstack_v0.14.2 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Versions (please complete the following information):**
 - OS: Linux
 - Terraform Version: 1.13.2
 - Provider version: 0.14.2
 - Elasticsearch Version: e.g. 9.2.5

**Additional context**
If required I can provide the TF code via a support request.

### PR DESCRIPTION
**Pull request by dimuon**
## Fix nil pointer panic in `getPackageInfo`

Closes #1782

### Problem

When a Fleet integration package version is removed from the EPM registry (e.g., `tcp` version `3.1.10` replaced by `3.1.11`), all Terraform operations crash with a nil pointer dereference during Read/refresh:

```
panic: runtime error: invalid memory address or nil pointer dereference
```

This blocks `terraform plan`, `terraform apply`, and `terraform destroy` — the only workaround is `terraform plan -refresh=false`.

### Root cause

`getPackageInfo` calls `fleet.GetPackage` with the exact version from the Terraform state. When that version no longer exists in the registry, the API returns a 404, `GetPackage` returns `(nil, nil)`, and the code dereferences the nil pointer when storing into the cache:

```go
knownPackages.Store(getPackageCacheKey(name, version), *pkg) // panic
```

### Fix

1. **Try exact version first, fall back to installed** — `getPackageInfo` now tries the exact version first. If the version is not found (404), it falls back to calling `fleet.GetPackage` without a version, which returns the currently installed package info. This preserves correct defaults when the version exists, while gracefully handling removed versions.

2. **Warning on version fallback** — when the exact version is not found and the fallback is used, a warning diagnostic is emitted so the user knows their `integration_version` is stale and defaults may differ.

3. **Nil guard on `GetPackage` result** — if the package is not found even without a version, return a warning (not an error) and a nil `pkg`. Downstream code already handles `nil` package info gracefully (empty defaults map, core state fields come from the policy API response).

4. **Nil guards on `policy.Package`** — added nil checks in `create.go`, `read.go`, and `update.go` before accessing `policy.Package.Name`/`.Version`. Returns an error diagnostic since without package info we can't populate required state fields.

### Tests

| Test | What it verifies |
|------|-----------------|
| `TestGetPackageInfo_PackageNotFound` | Both exact and fallback return 404 → no panic, nil pkg, warning diagnostics |
| `TestGetPackageInfo_Success` | Exact version found → package info returned correctly |
| `TestGetPackageInfo_CacheHit` | Cached entry → returned without HTTP call |
| `TestGetPackageInfo_FallbackToInstalled` | Exact version 404, fallback succeeds → installed package returned with warning |
| `TestAccResourceIntegrationPolicy` | Acceptance test passes end-to-end |

### CODE REVIEW

File: internal/fleet/integration_policy/resource_test.go [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+		require.NoError(t, json.NewEncoder(w).Encode(resp))
+	}))
+
+	pkg, diags := getPackageInfo(context.Background(), client, "tcp", "3.1.11")
+
+	require.False(t, diags.HasError())
+	require.NotNil(t, pkg)
+	assert.Equal(t, "tcp", pkg.Name)
+	assert.Equal(t, "3.1.11", pkg.Version)
+}
```
[the remark this answers is not in the document]
Comment (dimuon) [reply internal/fleet/integration_policy/resource_test.go:90]: Addressed in https://github.com/elastic/terraform-provider-elasticstack/pull/1913/commits/ef9f5d53327b1f15d5c465572be6ffe72dd8f5ac

File: internal/fleet/integration_policy/resource.go
Comment (tobio) [inline internal/fleet/integration_policy/resource.go:100]: It's likely more reliable to call `GetPackage` without any version in this case. It will return the currently installed version, rather than filter to the specifically requested version.

**Review by tobio — COMMENTED** [review]
LGTM, though I think we should remove the version requirement here to so we get the package info in most cases.

Needs a changelog entry too.

File: internal/fleet/integration_policy/resource.go
Comment (dimuon) [reply internal/fleet/integration_policy/resource.go:100]: Yeah, querying without a specific version would be more robust here. However, looking at the generated Kibana API client, the only available endpoint is `GetFleetEpmPackagesPkgnamePkgversion` which requires both name and version as path parameters - there's no version-less `GetFleetEpmPackagesPkgname` variant available. Do you know if that endpoint exists in the Kibana API spec? If not, I think the nil check is a reasonable pragmatic fix for now to prevent the panic.

Comment (tobio) [reply internal/fleet/integration_policy/resource.go:100]: IIRC just passing `""` as the version works as you'd expect.

Comment (dimuon) [reply internal/fleet/integration_policy/resource.go:100]: Addressed in https://github.com/elastic/terraform-provider-elasticstack/pull/1913/commits/9752261d542fdcb33d311da6f65835b0d26afcee

Comment (dimuon) [reply internal/fleet/integration_policy/resource.go:100]: Acc tests fail for stack version 8.10.3 - 8.19.9. 
Changed the solution to fetch the exact version first and then fallback to the installed one.
