### PR TITLE
Fix request dump debug log

### LINKED ISSUE #258: [Bug] Dump request is not working when debug mode
**Describe the bug**
Dump request is not working when debug mode.

**To Reproduce**
1. TF configuration used
```
resource "elasticstack_elasticsearch_index" "test" {
  name = "test"
  number_of_shards   = 1

  mappings = jsonencode({
    "dynamic": "true",
  })
}

```
3. TF operations to execute to get the error
`TF_LOG=DEBUG terraform plan` and `TF_LOG=DEBUG terraform apply`
5. See the error in the output '...'

**Expected behavior**
The request dump is showed as a debug log.

**Debug output**
Run `terraform` command with `TF_LOG=trace` and provide extended information on TF operations.
```
2023-01-16T15:32:38.324-0500 [DEBUG] provider.terraform-provider-elasticstack_v0.5.0: elasticsearch API request dump error: &errors.errorString{s:"unsupported protocol scheme \"\""}: tf_resource_type=elasticstack_elasticsearch_security_system_user tf_rpc=ApplyResourceChange tf_provider_addr=registry.terraform.io/elastic/elasticstack @module=elasticstack tf_mux_provider=*schema.GRPCProviderServer tf_req_id=6c517aac-434a-184a-88fa-9f459c294e9f @caller=github.com/elastic/terraform-provider-elasticstack/internal/clients/debug.go:45 timestamp=2023-01-16T15:32:38.324-0500
```

We can see the same error in the below issue too.
https://github.com/elastic/terraform-provider-elasticstack/issues/248

**Screenshots**

**Versions (please complete the following information):**
 - OS: Mac OS
 - Terraform Version 1.0.0
 - Provider version 0.5.0
 - Elasticsearch Version 8.0.0

**Additional context**

### PR DESCRIPTION
**Pull request by k-yomo**
Resolves #258 

`httputil.DumpRequestOut` is actually executing dummy [RondTrip](https://github.com/golang/go/blob/733ba921875ea11088f1f447cbca418f651aae5c/src/net/http/httputil/dump.go#L146) and it causes following error since the schema and host is not set at the point.
`request dump error: &errors.errorString{s:"unsupported protocol scheme \"\""}`

This PR changes the method to use `httputil.DumpRequest` which can work with an incomplete url.
```
2023-01-25T01:36:36.976+0900 [DEBUG] provider.terraform-provider-elasticstack: elasticsearch API Request Details:
---[ REQUEST ]---------------------------------------
GET /products?flat_settings=true HTTP/1.1


-----------------------------------------------------: @module=elasticstack tf_mux_provider=*schema.GRPCProviderServer tf_provider_addr=registry.terraform.io/elastic/elasticstack tf_rpc=ApplyResourceChange @caller=/Users/k-yomo/go/src/github.com/k-yomo/terraform-provider-elasticstack/internal/clients/debug.go:46 tf_req_id=6f651534-de0f-0549-41c9-ce9789c53b9f tf_resource_type=elasticstack_elasticsearch_index timestamp=2023-01-25T01:36:36.976+0900
```

### CODE REVIEW

File: internal/clients/debug.go [hunk 1]
```diff
@@ -38,7 +38,7 @@ func newDebugTransport(name string, transport esapi.Transport) *debugTransport {
 
 func (d *debugTransport) Perform(r *http.Request) (*http.Response, error) {
 	ctx := r.Context()
-	reqData, err := httputil.DumpRequestOut(r, true)
+	reqData, err := httputil.DumpRequest(r, true)
```
Comment (tobio) [inline internal/clients/debug.go]: From the [docs](https://pkg.go.dev/net/http/httputil#DumpRequest)

> It should only be used by servers to debug client requests

I think that we should be either using the build in go-elasticsearch [loggers](https://github.com/elastic/go-elasticsearch/blob/main/_examples/logging/default.go) or if using `tflog.*` was important implementing a [custom logger](https://github.com/elastic/go-elasticsearch/blob/main/_examples/logging/custom.go)

**Review by tobio — COMMENTED** [review]
I know this is a super quick fix, but we could simplify the tf provider by using the go-elasticsearch Logger interface.

**Comment by tobio** [comment]
@webfella are you able to take a look at my changes here?

**Review by webfella — DISMISSED** [review]
LGTM 🥟

**Review by tobio — APPROVED** [review]
